### ISSUE TITLE
What is a toast? 

### ISSUE THREAD

**Issue by edent** [jackbsteinberg/std-toast#26]
Please could you explain what a "toast" is - and provide some sample screenshots?

At the moment, the spec reads like it is `alert("I'm a toast!);` which I don't think is your intention.

Juding from a Twitter thread, I'm not alone in this confusion. https://twitter.com/stevefaulkner/status/1138933155866513409

 I always associate Toasts with those annoying Android popups which mysteriously appear and disappear. Again, I'm not quite sure if that's what you're going for. Some mockups or screenshots would help clarify.

**Comment by monico-moreno** [comment]
fyi 👉 #30   😉

**Comment by domenic** [comment]
Did you see https://github.com/jackbsteinberg/std-toast/tree/master/study-group ? In particular https://github.com/jackbsteinberg/std-toast/blob/master/study-group/Visual-Study.md ?

**Comment by edent** [comment]
@domenic I didn't see those linked from the readme. GitHub's colour scheme isn't great on mobile - so I didn't spot any links.  That's why I suggested screenshots on the "front page".

**Comment by aardrian** [comment]
I see the PR to address this.

However, even that refined definition of _toast_ leans on a visual metaphor. It is meaningless to many users and for others implies or asserts a kind of interaction as necessary.

Just as many developers choose an `<h2>` over a more appropriate `<h4>` because they want bolder, bigger text, developers may choose this new element based on how it moves or where it lives on the screen instead of by the features it brings.

Suggest defining toast using the existing roles already specced in ARIA (see #25 ) and naming it based on a word that captures those roles. Which means before proposing a proper name, agreeing on the roles, which means defining the problem as a user need not a developer need.
